### ISSUE TITLE
Can we add the ability to process array values in local yml files as well?

### ISSUE THREAD

**Issue by jennwah** [buru/locales_export_import#6]
Feature expected:

Should be able to export array values from yaml key as well, for example

https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml 

we might have translations for these yaml keys

```
date:
    abbr_day_names:
    - Sun
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
    abbr_month_names:
    - 
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - Jun
    - Jul
    - Aug
    - Sep
    - Oct
    - Nov
    - Dec
```

csv output could be 
date.abbr_day_names [Sun, Mon, Tue, Wed,Thu, Fri, Sat] 

And when converting back from csv to yml,

the same output as yml file originally. 

I think this would be a great feature to be added
